### ISSUE TITLE
support rss

### ISSUE THREAD

**Issue by GHolk** [yiyu0x/yiyu0x.github.io#1]
覺得你的部落格內容很有趣，請問有沒有興趣增加 rss 訂閱的功能？ rss 或 atom 都可以。

**Comment by yiyu0x** [comment]
抱歉，不知道爲什麼沒收到通知。在我的 blog 尾端加上 atom.xml 就有 rss 囉。
另外，我現在也有在首頁放上 rss 連結，下次太久沒回覆可以考慮直接寄信給我，感謝支持！

**Comment by GHolk** [comment]
感謝。

另外你的 [從駭客角度告訴你為何不要隨意複製指令] 一文中，
提到用 copy event 改寫複製的內容的作法蠻有趣的，
可能會收錄到 [我們社團的雙周刊](http://weekly.ccns.io) 分享中。
有興趣歡迎訂閱 :)

**Comment by GHolk** [comment]
另外貴部落格的留言功能似乎壞了？先留在這裡：

關於使用 copy 事件改寫複製內容的作法，其實還有一些技巧可以用。像是直接把複製的內容改成另完全不同的指令，不一定要用後綴 `| sh` 的作法。甚至可以直接在字串內容附加換行符，貼上時就直接執行，仔細想想還真可怕。

不過 linux 下的中鍵貼下似乎沒辦法被更改？

**Comment by yiyu0x** [comment]
感謝您的提醒，我稍後再檢查一下相關設定。

該原理是透過瀏覽器偵測複製行為的事件，並且修改剪貼板內容。只要 Linux 中的複製能被 JS 偵測，理論上就有辦法修改。

另外，我訂閱您的社團雙週刊，但訂閱按鈕的連結似乎也壞掉了。

**Comment by GHolk** [comment]
因為周刊系統昨天才開始重啟。系統是幾年前蓋的，但沒有出刊；最近又想重啟計劃，昨天才開始調校，好了會再告知你。或你有興趣可以到 [ccns 周刊的倉庫](https://github.com/CCNS/CCNS_Weekly_Web) 查看或發 issue 。

**Comment by GHolk** [comment]
剛剛詢問的結果，現在應該可以訂閱了。
[臉書發文](https://www.facebook.com/ncku.ccns/posts/1656305024571689)
時間是三小時前，應該代表三小時前已經是正式上線了。
